<a href="https://colab.research.google.com/github/admenezes/spam-classifier/blob/main/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This program detects if an email is spam (1) or not (0)

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import nltk
import sklearn
from nltk.corpus import stopwords
import string

In [ ]:
# Load the data
from google.colab import files
f = files.upload()

Saving enron.csv to enron.csv


In [ ]:
# Read the file
df = pd.read_csv('enron.csv', header = None, delimiter=',')

#Get the column names
df.columns = ['Text','Spam']

# Print first 5 rows
# df[:5,:]
df.head(5)

Text  Spam
0             Subject: christmas tree farm pictures      0
1  Subject: vastar resources , inc . gary , produ...     0
2  Subject: calpine daily gas nomination - calpin...     0
3  Subject: re : issue fyi - see note below - alr...     0
4  Subject: meter 7268 nov allocation fyi . - - -...     0

In [ ]:
#Print the shape (Get the number of rows and cols)
df.shape

(4302, 2)

In [ ]:
#Checking for duplicates and removing them
df.drop_duplicates(inplace = True)
#Show the new shape (number of rows & columns)
df.shape

(4059, 2)

In [ ]:
#Show the number of missing (NAN, NaN, na) data for each column
df.isnull().sum()

Text    0
Spam    0
dtype: int64

In [ ]:
#Need to download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
#Tokenization (a list of tokens), will be used as the analyzer
#1.Punctuations are [!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]
#2.Stop words in natural language processing, are useless words (data).
def process_text(text):
    
    #1 Remove Punctuations
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    #2 Remove Stop Words
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #3 Return a list of clean words
    return clean_words

In [ ]:
#Show the Tokenization (a list of tokens )
df['Text'].head().apply(process_text)

0           [Subject, christmas, tree, farm, pictures]
1    [Subject, vastar, resources, inc, gary, produc...
2    [Subject, calpine, daily, gas, nomination, cal...
3    [Subject, issue, fyi, see, note, already, done...
4    [Subject, meter, 7268, nov, allocation, fyi, f...
Name: Text, dtype: object

In [ ]:
#Convert the text into a matrix of token counts (number of unique words)
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['Text'])

In [ ]:
#Get the shape of messages_bow
messages_bow.shape

(4059, 40752)

In [ ]:
#Split data into 80% training & 20% testing data sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['Spam'], test_size = 0.20, random_state = 0)

In [ ]:
#Testing features and labels
X_test.shape, y_test.shape

((812, 40752), (812,))

In [ ]:
#Training features and labels
X_train.shape, y_train.shape

((3247, 40752), (3247,))

In [ ]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(hidden_layer_sizes = (6,2), activation = 'tanh',learning_rate = 'adaptive', max_iter = 1000)
classifier.fit(X_train, y_train)

MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(6, 2), learning_rate='adaptive',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
#Print the first 30 predictions
check1 = classifier.predict(X_train)
print(check1[:30])
#Print the first 30 Actual Label
check2 = y_train.values
print(check2[:30])

[0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0]
[0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0]


In [ ]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train ,pred ))
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print('\nAccuracy: ', accuracy_score(y_train,pred)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2761
           1       1.00      1.00      1.00       486

    accuracy                           1.00      3247
   macro avg       1.00      1.00      1.00      3247
weighted avg       1.00      1.00      1.00      3247

Confusion Matrix: 
 [[2761    0]
 [   1  485]]

Accuracy:  0.9996920234062211


In [ ]:
#Print the first 30 predictions
check1 = classifier.predict(X_test)
print(check1[:30])
#Print the first 30 Actual Label
check2 = y_test.values
print(check2[:30])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]


In [ ]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test ,pred ))
print('Confusion Matrix: \n', confusion_matrix(y_test,pred))
print()
print('Accuracy: ', accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       680
           1       0.97      0.87      0.92       132

    accuracy                           0.98       812
   macro avg       0.98      0.93      0.95       812
weighted avg       0.98      0.98      0.97       812

Confusion Matrix: 
 [[677   3]
 [ 17 115]]

Accuracy:  0.9753694581280788


In [ ]:
# CROSS VALIDATION SCORE
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, X_test, y_test, cv=10)

# Print the accuracy of each fold:
print(scores)
print(' ')
# Print the mean accuracy of all 10 folds
print('The average accuracy across all 10 folds is: ',scores.mean())